### ISSUE TITLE
facebook open graph header 

### ISSUE THREAD

**Issue by bluehirsch** [simonrepp/playvienna.com#17]
clara probiert das mal aus :D

**Comment by simonrepp** [comment]
:+1:

**Comment by simonrepp** [comment]
`<meta property="image" content="http://www.playvienna.comgames/personal-adventure-automat.jpg" />`

Achtung der Link zum Bild ist nicht nur "not final", sondern kaputt - wenn möglich bitte nur funktionierende Sachen hinzufügen :) (und was noch nicht fertig ist daweil noch weglassen)

**Comment by bluehirsch** [comment]
ja aber vor allem weil ich nicht weiß welches foto wir verwenden sollen und ich nicht wusste wie ich genau an bilder komme oder sowas.

**Comment by simonrepp** [comment]
wenn du was von mir dafür brauchst dann schreibs mir und ich helf dir :) ich wollte nur drauf aufmerksam machen, dass das problematisch ist kaputte sachen zu commiten, weil bis sich wer drum kümmert (und man weiss vorher selten wann man wieder zeit hat dazu zu kommen) ist das kaputt. wenn jetzt, hypothetisch gesprochen, jedes mal wenn irgendeiner unserer fans unsere website auf facebook posten will, ein "Image not found" oder sonstirgendein fehler als thumbnail aufscheint, dann hilft das halt nicht dass du mir auf github erklärt hast warum dass passiert ist, es ist trotzdem kaputt. :) nächstes mal einfach dran denken. :)

**Comment by bluehirsch** [comment]
ok :)

**Comment by simonrepp** [comment]
@bluehirsch Machst du das noch? Wenn du was brauchst musst du mir eine konkrete Frage schreiben oder wir machen uns eine Arbeitssession aus :)

**Comment by simonrepp** [comment]
Whoops :)

**Comment by simonrepp** [comment]
8e73ace61ecdfa1bc0e93027e08c35255dafc7b0 :ok:

**Comment by bluehirsch** [comment]
Arbeitssession! :D 
sorry simon, ich muss zur zeit ein bisschen mehr für die uni tun, als ich die letzten monate gemacht hab, und deshalb ist grad homepage und so etwas weiter hinten in meiner to-do liste ;) 

also im grunde wusste ich nicht wie ich ein foto auf die homepage hochladen kann bzw wie ich einen richtigen link bekomme für ein foto, dass vllt auch du schon irgendwo für die homepage verwendest.

**Comment by simonrepp** [comment]
Ok kein Problem; hast du den Issue jetzt unabsichtlich wieder aufgemacht? Ich hab eigentlich alles gemacht was zu tun war, ausser du hast noch was anderes vor wovon ich nicht weiss.
